title: Datauto
description: "Automate Your Data Analysis with AI"
url: "https://datauto.dev"
baseurl: ""


  author: Mounish Mesa
  email: mounish@datauto.dev

github_username: mounishmesa
linkedin_username: mounish-jm

# Try a different theme
remote_theme: pages-themes/minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - about.md
  - projects.md
  - tutorials.md
  - contact.md
